### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by zhangabner** [jimthompson5802/mlflow_demo#15]
bash ./build_images
ERROR: Need service name for --build-arg option

# build Docker images for demo containers
# this must be run with the working directory set to the directory
# containing the docker-compose.yml file.

docker-compose build \
    --build-arg MLFLOW_VERSION=${MLFLOW_VERSION:-1.4.0} \
    --build-arg MLFLOW_VERSION_TO_INSTALL=${MLFLOW_VERSION_TO_INSTALL} \

# mlflow version to install
export MLFLOW_VERSION=1.4.0
# directory containing demonstration source code
export MLFLOW_DEMO_DIRECTORY=/home/newwen5/mlflow_demo
# directory to hold mlflow tracking and artifacts
export MLFLOW_TRACKING_DIRECTORY=/home/newwen5/mlflow_server

**Comment by jimthompson5802** [comment]
@zhangabner I need additional information to help you with this problem.  Please provide the following:

* Post the contents of your file `setup_environment_variables`
* Send output from this command `env | grep ^MLFLOW`

thank you.

**Comment by zhangabner** [comment]
Hi Jim

Thanks for reply. the following is

   - Post the contents of your file setup_environment_variables
   -


###
# Set up environment variables to control building and
# running demonstration mlflow Docker containers
###

# mlflow version to install
export MLFLOW_VERSION=1.4.0

# directory containing demonstration source code
export MLFLOW_DEMO_DIRECTORY=/home/newwen/mlflow_demo

# directory to hold mlflow tracking and artifacts
export MLFLOW_TRACKING_DIRECTORY=/home/newwen/mlflow_server

# mflow tracking server URI
export MLFLOW_TRACKING_URI=http://mlflow_tracker:5000

# backend store
#export MLFLOW_BACKEND_STORE=postgresql://mlflow_user:mlflow_pw@pgdb
/mlflow_db
export MLFLOW_BACKEND_STORE=/tracking

###
# EXAMPLES
# MLFLOW_VERSION_TO_INSTALL="mlflow"    Current version in PyPi
# MLFLOW_VERSION_TO_INSTALL="mlflow==${MLFLOW_VERSION}"   Specific version
from PyPi
# MLFLOW_VERSION_TO_INSTALL="git+
https://github.com/mlflow/mlflow.git@vx.y.z#egg=mlflow"  specific version
from github
###
# uncomment following to install mlflow from pypi
#export MLFLOW_VERSION_TO_INSTALL="mlflow==${MLFLOW_VERSION}"

# uncomment following to install mlflow from github
export MLFLOW_VERSION_TO_INSTALL="git+
https://github.com/mlflow/mlflow.git@v${MLFLOW_VERSION}#egg=mlflow"
 specific version from github


   - Send output from this command `env | grep MLFLOW

(base) newwen@newwen-ECQ3-0:~/mlflow_demo/run_demo$ env | grep MLFLOW
MLFLOW_VERSION_TO_INSTALL=git+
https://github.com/mlflow/mlflow.git@v1.4.0#egg=mlflow
MLFLOW_BACKEND_STORE=/tracking
MLFLOW_DEMO_DIRECTORY=/home/newwen/mlflow_demo
MLFLOW_VERSION=1.4.0
MLFLOW_TRACKING_URI=http://mlflow_tracker:5000
MLFLOW_TRACKING_DIRECTORY=/home/newwen/mlflow_server


build_images:
# build Docker images for demo containers
# this must be run with the working directory set to the directory
# containing the docker-compose.yml file.

docker-compose build \
    --build-arg MLFLOW_VERSION=${MLFLOW_VERSION:-1.4.0} \
    --build-arg MLFLOW_VERSION_TO_INSTALL=${MLFLOW_VERSION_TO_INSTALL} \

(base) newwen@newwen-ECQ3-0:~/mlflow_demo/run_demo$ bash ./build_images
ERROR: Need service name for --build-arg option

Jim Thompson <notifications@github.com> 于2019年12月9日周一 上午12:53写道：

**Comment by zhangabner** [comment]
(base) newwen@newwen-ECQ3-0:~/mlflow_demo/run_demo$ sudo docker-compose up
WARNING: The MLFLOW_BACKEND_STORE variable is not set. Defaulting to a
blank string.
WARNING: The MLFLOW_TRACKING_URI variable is not set. Defaulting to a blank
string.
Building py
Step 1/5 : FROM continuumio/anaconda3:latest
 ---> 5fbf7bac70a0
Step 2/5 : ARG MLFLOW_VERSION_TO_INSTALL
 ---> Using cache
 ---> d7163774a606
Step 3/5 : RUN echo "\n###\n# BUILDING mlflow_python image with mlflow
${MLFLOW_VERSION_TO_INSTALL}\n###"
 ---> Using cache
 ---> d32133c98b7e
Step 4/5 : RUN conda install -c conda-forge xgboost
 ---> Using cache
 ---> 743cedc35269
Step 5/5 : RUN pip install ${MLFLOW_VERSION_TO_INSTALL}
 ---> Running in 648aa9d8d29b
ERROR: You must give at least one requirement to install (see "pip help
install")
ERROR: Service 'py' failed to build: The command '/bin/sh -c pip install
${MLFLOW_VERSION_TO_INSTALL}' returned a non-zero code: 1



 docker-compose  pull pgadmin
Pulling pgadmin (dpage/pgadmin4:latest)...
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket -
is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST
environment variable.

zhang abner <abner.zhangxinbin.anz@gmail.com> 于2019年12月9日周一 上午9:04写道：

**Comment by jimthompson5802** [comment]
@zhangabner   Couple of questions:
1) What is the current working directory when you run `bash ./build_images`?  
2) It appears you want mlflow 1.4.0.  Why are you referencing the GitHub as the source instead of PyPi?   Since 1.4.0 is in PyPi, I use that as the source.

This is how my MLFLOW environment variables are set
```
Jim-MacBook-Pro:jim run_demo[514]$ env | grep ^MLFLOW
MLFLOW_VERSION_TO_INSTALL=mlflow==1.4.0
MLFLOW_BACKEND_STORE=/tracking
MLFLOW_DEMO_DIRECTORY=/Users/jim/Desktop/databricks_mlflow/mlflow_demo
MLFLOW_VERSION=1.4.0
MLFLOW_TRACKING_URI=http://mlflow_tracker:5000
MLFLOW_TRACKING_DIRECTORY=/Users/jim/Desktop/databricks_mlflow/mlflow_server
Jim-MacBook-Pro:jim run_demo[515]$ 
```

With this setting and with current working directory set to `run_demo`, the 'bash ./build_images` works for me.

**Comment by zhangabner** [comment]
I follow the steps:
    Change working directory to run_demo
    Update contents of ./setup_environment_variables to specify values for
the required environment variables.

MLFLOW_VERSION
MLFLOW_VERSION_TO_INSTALL
MFLOW_DEMO_DIRECTORY
MLFLOW_TRACKING_DIRECTORY
MLFLOW_TRACKER_URL

(base) newwen@newwen-ECQ3-0:~/mlflow_demo/run_demo$ bash ./build_images
ERROR: Need service name for --build-arg option
(base) newwen@newwen-ECQ3-0:~/mlflow_demo/run_demo$ pwd
/home/newwen/mlflow_demo/run_demo


   1. It appears you want mlflow 1.4.0. Why are you referencing the GitHub
   as the source instead of PyPi? Since 1.4.0 is in PyPi, I use that as the
   source.

what do you mean by this?



Jim Thompson <notifications@github.com> 于2019年12月9日周一 上午11:53写道：

**Comment by jimthompson5802** [comment]
Instead of using this
```
export MLFLOW_VERSION_TO_INSTALL=git+https://github.com/mlflow/mlflow.git@v1.4.0#egg=mlflow
```

use this
```
export MLFLOW_VERSION_TO_INSTALL="mlflow==${MLFLOW_VERSION}"
```

**Comment by zhangabner** [comment]
###
# Set up environment variables to control building and
# running demonstration mlflow Docker containers
###

# mlflow version to install
export MLFLOW_VERSION=1.4.0

# directory containing demonstration source code
export MLFLOW_DEMO_DIRECTORY=/home/newwen/mlflow_demo

# directory to hold mlflow tracking and artifacts
export MLFLOW_TRACKING_DIRECTORY=/home/newwen/mlflow_server

# mflow tracking server URI
export MLFLOW_TRACKING_URI=http://mlflow_tracker:5000

# backend store
#export MLFLOW_BACKEND_STORE=postgresql://mlflow_user:mlflow_pw@pgdb
/mlflow_db
export MLFLOW_BACKEND_STORE=/tracking

###
# EXAMPLES
# MLFLOW_VERSION_TO_INSTALL="mlflow"    Current version in PyPi
# MLFLOW_VERSION_TO_INSTALL="mlflow==${MLFLOW_VERSION}"   Specific version
from PyPi
# MLFLOW_VERSION_TO_INSTALL="git+
https://github.com/mlflow/mlflow.git@vx.y.z#egg=mlflow"  specific version
from github
###
# uncomment following to install mlflow from pypi
export MLFLOW_VERSION_TO_INSTALL="mlflow==${MLFLOW_VERSION}"


# uncomment following to install mlflow from github
#export MLFLOW_VERSION_TO_INSTALL="git+
https://github.com/mlflow/mlflow.git@v${MLFLOW_VERSION}#egg=mlflow"
 specific version from github



docker-compose build \docker-compose build \
    --build-arg MLFLOW_VERSION=${MLFLOW_VERSION:-1.4.0} \
    --build-arg
MLFLOW_VERSION_TO_INSTALL=${MLFLOW_VERSION_TO_INSTALL:-1.4.0} \

(base) newwen@newwen-ECQ3-0:~/mlflow_demo/run_demo$ bash ./build_images
ERROR: Need service name for --build-arg option
(base) newwen@newwen-ECQ3-0:~/mlflow_demo/run_demo$ docker-compose up
Building py
Step 1/5 : FROM continuumio/anaconda3:latest
 ---> 5fbf7bac70a0
Step 2/5 : ARG MLFLOW_VERSION_TO_INSTALL
 ---> Using cache
 ---> d7163774a606
Step 3/5 : RUN echo "\n###\n# BUILDING mlflow_python image with mlflow
${MLFLOW_VERSION_TO_INSTALL}\n###"
 ---> Using cache
 ---> d32133c98b7e
Step 4/5 : RUN conda install -c conda-forge xgboost
 ---> Using cache
 ---> 743cedc35269
Step 5/5 : RUN pip install ${MLFLOW_VERSION_TO_INSTALL}
 ---> Running in f94e58e37557
ERROR: You must give at least one requirement to install (see "pip help
install")
ERROR: Service 'py' failed to build: The command '/bin/sh -c pip install
${MLFLOW_VERSION_TO_INSTALL}' returned a non-zero code: 1

is  MLFLOW_VERSION_TO_INSTALL   missing?

Jim Thompson <notifications@github.com> 于2019年12月9日周一 下午1:21写道：

**Comment by jimthompson5802** [comment]
What OS are you running on?

From what I can tell, you are not using a database for the backend.  Make sure to comment out or delete all the lines that follow these lines in `docker-compose.yml`:
```
###
# TO DISABLE DATABASE TRACKER COMPONENTS REMOVE
# OR COMMENT OUT ALL LINES FOLLOWING THIS COMMENT SECTION.
###
```

For me this works.

File contents for `setup_environment_variables`:
```
# mlflow version to install
export MLFLOW_VERSION=1.4.0

# directory containing demonstration source code
export MLFLOW_DEMO_DIRECTORY=/Users/jim/Desktop/databricks_mlflow/mlflow_demo

# directory to hold mlflow tracking and artifacts
export MLFLOW_TRACKING_DIRECTORY=/Users/jim/Desktop/databricks_mlflow/mlflow_server

# mflow tracking server URI
export MLFLOW_TRACKING_URI=http://mlflow_tracker:5000

# backend store
export MLFLOW_BACKEND_STORE=/tracking

# version of mlflow to install in containers
export MLFLOW_VERSION_TO_INSTALL="mlflow==${MLFLOW_VERSION}"
```

Set current working directory to `run_demo`.  These commands work for me.
```
Jim-MacBook-Pro:jim run_demo[515]$ pwd
/Users/jim/Desktop/databricks_mlflow/mlflow_demo/run_demo

Jim-MacBook-Pro:jim run_demo[516]$ . ./setup_environment_variables

Jim-MacBook-Pro:jim run_demo[517]$ env | grep ^MLFLOW
MLFLOW_VERSION_TO_INSTALL=mlflow==1.4.0
MLFLOW_BACKEND_STORE=/tracking
MLFLOW_DEMO_DIRECTORY=/Users/jim/Desktop/databricks_mlflow/mlflow_demo
MLFLOW_VERSION=1.4.0
MLFLOW_TRACKING_URI=http://mlflow_tracker:5000
MLFLOW_TRACKING_DIRECTORY=/Users/jim/Desktop/databricks_mlflow/mlflow_server

Jim-MacBook-Pro:jim run_demo[518]$ docker-compose build \
>     --build-arg MLFLOW_VERSION=${MLFLOW_VERSION} \
>     --build-arg MLFLOW_VERSION_TO_INSTALL=${MLFLOW_VERSION_TO_INSTALL}
pgdb uses an image, skipping
pgadmin uses an image, skipping
Building mlflow_tracker
Step 1/7 : FROM continuumio/miniconda3
 ---> 406f2b43ea59
Step 2/7 : ARG MLFLOW_VERSION
 ---> Running in 8f75684f0e9f
Removing intermediate container 8f75684f0e9f
 ---> 45cd2202c8cb
Step 3/7 : ARG MLFLOW_VERSION_TO_INSTALL
 ---> Running in 3432cdc53c47
Removing intermediate container 3432cdc53c47
 ---> 456b425cd27f
Step 4/7 : RUN echo "\n###\n# BUILDING mlflow_server image with mlflow ${MLFLOW_VERSION}\n###"
 ---> Running in a1430687914b

###
# BUILDING mlflow_server image with mlflow 1.4.0
###
Removing intermediate container a1430687914b
 ---> bd6230a415e3
Step 5/7 : RUN pip install ${MLFLOW_VERSION_TO_INSTALL} sqlalchemy==1.3.0 psycopg2-binary
 ---> Running in 94b66f4b76a9
Collecting mlflow==1.4.0
  Downloading https://files.pythonhosted.org/packages/4f/b5/675b32531c43f0f1445d727b63bc88b3f30467af9e27d0e7d4a243758dbb/mlflow-1.4.0.tar.gz (14.6MB)
Collecting sqlalchemy==1.3.0
  Downloading https://files.pythonhosted.org/packages/35/9e/5eb467ed50cdd8e88b808a7e65045020fa12b3b9c2ab51de0f452d269d4d/SQLAlchemy-1.3.0.tar.gz (5.9MB)
Collecting psycopg2-binary
  Downloading https://files.pythonhosted.org/packages/37/69/c964165696fddf611f518b31c20774cdb635a49d6a0bd5bc3a1deec549b3/psycopg2_binary-2.8.4-cp37-cp37m-manylinux1_x86_64.whl (2.9MB)
Collecting alembic (from mlflow==1.4.0)
  Downloading https://files.pythonhosted.org/packages/84/64/493c45119dce700a4b9eeecc436ef9e8835ab67bae6414f040cdc7b58f4b/alembic-1.3.1.tar.gz (1.1MB)
Collecting click>=7.0 (from mlflow==1.4.0)
  Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
Collecting cloudpickle (from mlflow==1.4.0)
  Downloading https://files.pythonhosted.org/packages/c1/49/334e279caa3231255725c8e860fa93e72083567625573421db8875846c14/cloudpickle-1.2.2-py2.py3-none-any.whl
Collecting databricks-cli>=0.8.7 (from mlflow==1.4.0)
  Downloading https://files.pythonhosted.org/packages/85/03/fb0c4d31559d48f15403ad88aefff8ae0dddbbeab273d198c20232a937c2/databricks-cli-0.9.1.tar.gz (45kB)
Requirement already satisfied: requests>=2.17.3 in /opt/conda/lib/python3.7/site-packages (from mlflow==1.4.0) (2.22.0)
Requirement already satisfied: six>=1.10.0 in /opt/conda/lib/python3.7/site-packages (from mlflow==1.4.0) (1.12.0)
Collecting Flask (from mlflow==1.4.0)
  Downloading https://files.pythonhosted.org/packages/9b/93/628509b8d5dc749656a9641f4caf13540e2cdec85276964ff8f43bbb1d3b/Flask-1.1.1-py2.py3-none-any.whl (94kB)
Collecting numpy (from mlflow==1.4.0)
  Downloading https://files.pythonhosted.org/packages/9b/af/4fc72f9d38e43b092e91e5b8cb9956d25b2e3ff8c75aed95df5569e4734e/numpy-1.17.4-cp37-cp37m-manylinux1_x86_64.whl (20.0MB)
Collecting pandas (from mlflow==1.4.0)
  Downloading https://files.pythonhosted.org/packages/63/e0/a1b39cdcb2c391f087a1538bc8a6d62a82d0439693192aef541d7b123769/pandas-0.25.3-cp37-cp37m-manylinux1_x86_64.whl (10.4MB)
Collecting python-dateutil (from mlflow==1.4.0)
  Downloading https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl (227kB)
Collecting protobuf>=3.6.0 (from mlflow==1.4.0)
  Downloading https://files.pythonhosted.org/packages/c8/bd/9609c681f655c4b85f4e4f4c99d42b68bca63ad8891c6924ba6696dee0bb/protobuf-3.11.1-cp37-cp37m-manylinux1_x86_64.whl (1.3MB)
Collecting gitpython>=2.1.0 (from mlflow==1.4.0)
  Downloading https://files.pythonhosted.org/packages/20/8c/4543981439d23c4ff65b2e62dddd767ebc84a8e664a9b67e840d1e2730d3/GitPython-3.0.5-py3-none-any.whl (455kB)
Collecting pyyaml (from mlflow==1.4.0)
  Downloading https://files.pythonhosted.org/packages/8d/c9/e5be955a117a1ac548cdd31e37e8fd7b02ce987f9655f5c7563c656d5dcb/PyYAML-5.2.tar.gz (265kB)
Collecting querystring_parser (from mlflow==1.4.0)
  Downloading https://files.pythonhosted.org/packages/4a/fa/f54f5662e0eababf0c49e92fd94bf178888562c0e7b677c8941bbbcd1bd6/querystring_parser-1.2.4.tar.gz

  <<<<<<<<<<<<< truncated >>>>>>>>>>>>>>>>>>>>>>..

  Stored in directory: /root/.cache/pip/wheels/bc/27/58/c6ef96e649962e9584a50f58d5b6abafb71a03512b2e381ad1
  Building wheel for querystring-parser (setup.py): started
  Building wheel for querystring-parser (setup.py): finished with status 'done'
  Created wheel for querystring-parser: filename=querystring_parser-1.2.4-cp37-none-any.whl size=7079 sha256=94d07545154404f6c1f8524f71f4ddaec8f36be2978dd1a382bd42e9cc65e819
  Stored in directory: /root/.cache/pip/wheels/1e/41/34/23ebf5d1089a9aed847951e0ee375426eb4ad0a7079d88d41e
  Building wheel for simplejson (setup.py): started
  Building wheel for simplejson (setup.py): finished with status 'done'
  Created wheel for simplejson: filename=simplejson-3.17.0-cp37-none-any.whl size=55461 sha256=2c91f8def2001ded7622dc2f003b88e1ac6e5a5467539ef15d301c9a8be9ab51
  Stored in directory: /root/.cache/pip/wheels/86/c0/83/dcd0339abb2640544bb8e0938aab2d069cef55e5647ce6e097
  Building wheel for Mako (setup.py): started
  Building wheel for Mako (setup.py): finished with status 'done'
  Created wheel for Mako: filename=Mako-1.1.0-cp37-none-any.whl size=75360 sha256=8e13768a9cf46c02344be8694b369021221b0e0953bea8da1d632f047ebc5e2a
  Stored in directory: /root/.cache/pip/wheels/98/32/7b/a291926643fc1d1e02593e0d9e247c5a866a366b8343b7aa27
  Building wheel for tabulate (setup.py): started
  Building wheel for tabulate (setup.py): finished with status 'done'
  Created wheel for tabulate: filename=tabulate-0.8.6-cp37-none-any.whl size=23274 sha256=2fbcda3a265d941b40ede0c1445468150d9264cc3d42b0a0925ac5548b3b97ba
  Stored in directory: /root/.cache/pip/wheels/9c/9b/f4/eb243fdb89676ec00588e8c54bb54360724c06e7fafe95278e
Successfully built mlflow alembic databricks-cli querystring-parser simplejson Mako tabulate
Installing collected packages: Mako, python-editor, alembic, tabulate, configparser, databricks-cli, protobuf, smmap2, gitdb2, gitpython, querystring-parser, simplejson, websocket-client, docker, sqlparse, gorilla, gunicorn, mlflow
Successfully installed Mako-1.1.0 alembic-1.3.1 configparser-4.0.2 databricks-cli-0.9.1 docker-4.1.0 gitdb2-2.0.6 gitpython-3.0.5 gorilla-0.3.0 gunicorn-20.0.4 mlflow-1.4.0 protobuf-3.11.1 python-editor-1.0.4 querystring-parser-1.2.4 simplejson-3.17.0 smmap2-2.0.5 sqlparse-0.3.0 tabulate-0.8.6 websocket-client-0.56.0
Removing intermediate container c6fe2d782d07
 ---> 848e62e7dd76
[Warning] One or more build-args [MLFLOW_VERSION] were not consumed
Successfully built 848e62e7dd76
Successfully tagged mlflow_py_demo:latest
Jim-MacBook-Pro:jim run_demo[519]$
```

**Comment by zhangabner** [comment]
I update to ubuntu 18, and the codes work now.

Thank you for the cdoe.

Jim Thompson <notifications@github.com> 于2019年12月9日周一 下午10:12写道：

**Comment by jimthompson5802** [comment]
Glad to hear it works.
